
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace FontAwesome.WPF {
	using System.ComponentModel;
	///<summary>
	///	FontAwesome v4.7.0 by Dave Gandy (@davegandy)
	///	The iconic font and CSS toolkit
	///	License http://fontawesome.io/license (Font: v4.7.0, C#: MIT License)
	///</summary>
	///<see href="http://fontawesome.io" />
	///<seealso href="https://github.com/FortAwesome/Font-Awesome" />
	///<seealso href="https://github.com/charri/Font-Awesome-WPF" />
	public enum FontAwesomeIcon {
		///<summary>Set this value to show no icon.</summary>
		None = 0x0,
		[Description("500px")]
		_500Px = 0xf26e,
		[Description("Accessible Icon")]
		AccessibleIcon = 0xf368,
		[Description("Accusoft")]
		Accusoft = 0xf369,
		[Description("Acquisitions Incorporated")]
		AcquisitionsIncorporated = 0xf6af,
		[Description("Ad")]
		Ad = 0xf641,
		[Description("Address Book")]
		AddressBook = 0xf2b9,
		[Description("Address Card")]
		AddressCard = 0xf2bb,
		[Description("adjust")]
		Adjust = 0xf042,
		[Description("App.net")]
		Adn = 0xf170,
		[Description("Adobe")]
		Adobe = 0xf778,
		[Description("Adversal")]
		Adversal = 0xf36a,
		[Description("affiliatetheme")]
		Affiliatetheme = 0xf36b,
		[Description("Air Freshener")]
		AirFreshener = 0xf5d0,
		[Description("Airbnb")]
		Airbnb = 0xf834,
		[Description("Algolia")]
		Algolia = 0xf36c,
		[Description("align-center")]
		AlignCenter = 0xf037,
		[Description("align-justify")]
		AlignJustify = 0xf039,
		[Description("align-left")]
		AlignLeft = 0xf036,
		[Description("align-right")]
		AlignRight = 0xf038,
		[Description("Alipay")]
		Alipay = 0xf642,
		[Description("Allergies")]
		Allergies = 0xf461,
		[Description("Amazon")]
		Amazon = 0xf270,
		[Description("Amazon Pay")]
		AmazonPay = 0xf42c,
		[Description("ambulance")]
		Ambulance = 0xf0f9,
		[Description("American Sign Language Interpreting")]
		AmericanSignLanguageInterpreting = 0xf2a3,
		[Description("Amilia")]
		Amilia = 0xf36d,
		[Description("Anchor")]
		Anchor = 0xf13d,
		[Description("Android")]
		Android = 0xf17b,
		[Description("AngelList")]
		Angellist = 0xf209,
		[Description("Angle Double Down")]
		AngleDoubleDown = 0xf103,
		[Description("Angle Double Left")]
		AngleDoubleLeft = 0xf100,
		[Description("Angle Double Right")]
		AngleDoubleRight = 0xf101,
		[Description("Angle Double Up")]
		AngleDoubleUp = 0xf102,
		[Description("angle-down")]
		AngleDown = 0xf107,
		[Description("angle-left")]
		AngleLeft = 0xf104,
		[Description("angle-right")]
		AngleRight = 0xf105,
		[Description("angle-up")]
		AngleUp = 0xf106,
		[Description("Angry Face")]
		Angry = 0xf556,
		[Description("Angry Creative")]
		Angrycreative = 0xf36e,
		[Description("Angular")]
		Angular = 0xf420,
		[Description("Ankh")]
		Ankh = 0xf644,
		[Description("App Store")]
		AppStore = 0xf36f,
		[Description("iOS App Store")]
		AppStoreIos = 0xf370,
		[Description("Apper Systems AB")]
		Apper = 0xf371,
		[Description("Apple")]
		Apple = 0xf179,
		[Description("Fruit Apple")]
		AppleAlt = 0xf5d1,
		[Description("Apple Pay")]
		ApplePay = 0xf415,
		[Description("Archive")]
		Archive = 0xf187,
		[Description("Archway")]
		Archway = 0xf557,
		[Description("Alternate Arrow Circle Down")]
		ArrowAltCircleDown = 0xf358,
		[Description("Alternate Arrow Circle Left")]
		ArrowAltCircleLeft = 0xf359,
		[Description("Alternate Arrow Circle Right")]
		ArrowAltCircleRight = 0xf35a,
		[Description("Alternate Arrow Circle Up")]
		ArrowAltCircleUp = 0xf35b,
		[Description("Arrow Circle Down")]
		ArrowCircleDown = 0xf0ab,
		[Description("Arrow Circle Left")]
		ArrowCircleLeft = 0xf0a8,
		[Description("Arrow Circle Right")]
		ArrowCircleRight = 0xf0a9,
		[Description("Arrow Circle Up")]
		ArrowCircleUp = 0xf0aa,
		[Description("arrow-down")]
		ArrowDown = 0xf063,
		[Description("arrow-left")]
		ArrowLeft = 0xf060,
		[Description("arrow-right")]
		ArrowRight = 0xf061,
		[Description("arrow-up")]
		ArrowUp = 0xf062,
		[Description("Alternate Arrows")]
		ArrowsAlt = 0xf0b2,
		[Description("Alternate Arrows Horizontal")]
		ArrowsAltH = 0xf337,
		[Description("Alternate Arrows Vertical")]
		ArrowsAltV = 0xf338,
		[Description("Artstation")]
		Artstation = 0xf77a,
		[Description("Assistive Listening Systems")]
		AssistiveListeningSystems = 0xf2a2,
		[Description("asterisk")]
		Asterisk = 0xf069,
		[Description("Asymmetrik, Ltd.")]
		Asymmetrik = 0xf372,
		[Description("At")]
		At = 0xf1fa,
		[Description("Atlas")]
		Atlas = 0xf558,
		[Description("Atlassian")]
		Atlassian = 0xf77b,
		[Description("Atom")]
		Atom = 0xf5d2,
		[Description("Audible")]
		Audible = 0xf373,
		[Description("Audio Description")]
		AudioDescription = 0xf29e,
		[Description("Autoprefixer")]
		Autoprefixer = 0xf41c,
		[Description("avianex")]
		Avianex = 0xf374,
		[Description("Aviato")]
		Aviato = 0xf421,
		[Description("Award")]
		Award = 0xf559,
		[Description("Amazon Web Services (AWS)")]
		Aws = 0xf375,
		[Description("Baby")]
		Baby = 0xf77c,
		[Description("Baby Carriage")]
		BabyCarriage = 0xf77d,
		[Description("Backspace")]
		Backspace = 0xf55a,
		[Description("backward")]
		Backward = 0xf04a,
		[Description("Bacon")]
		Bacon = 0xf7e5,
		[Description("Bahá'í")]
		Bahai = 0xf666,
		[Description("Balance Scale")]
		BalanceScale = 0xf24e,
		[Description("Balance Scale (Left-Weighted)")]
		BalanceScaleLeft = 0xf515,
		[Description("Balance Scale (Right-Weighted)")]
		BalanceScaleRight = 0xf516,
		[Description("ban")]
		Ban = 0xf05e,
		[Description("Band-Aid")]
		BandAid = 0xf462,
		[Description("Bandcamp")]
		Bandcamp = 0xf2d5,
		[Description("barcode")]
		Barcode = 0xf02a,
		[Description("Bars")]
		Bars = 0xf0c9,
		[Description("Baseball Ball")]
		BaseballBall = 0xf433,
		[Description("Basketball Ball")]
		BasketballBall = 0xf434,
		[Description("Bath")]
		Bath = 0xf2cd,
		[Description("Battery Empty")]
		BatteryEmpty = 0xf244,
		[Description("Battery Full")]
		BatteryFull = 0xf240,
		[Description("Battery 1/2 Full")]
		BatteryHalf = 0xf242,
		[Description("Battery 1/4 Full")]
		BatteryQuarter = 0xf243,
		[Description("Battery 3/4 Full")]
		BatteryThreeQuarters = 0xf241,
		[Description("Battle.net")]
		BattleNet = 0xf835,
		[Description("Bed")]
		Bed = 0xf236,
		[Description("beer")]
		Beer = 0xf0fc,
		[Description("Behance")]
		Behance = 0xf1b4,
		[Description("Behance Square")]
		BehanceSquare = 0xf1b5,
		[Description("bell")]
		Bell = 0xf0f3,
		[Description("Bell Slash")]
		BellSlash = 0xf1f6,
		[Description("Bezier Curve")]
		BezierCurve = 0xf55b,
		[Description("Bible")]
		Bible = 0xf647,
		[Description("Bicycle")]
		Bicycle = 0xf206,
		[Description("Biking")]
		Biking = 0xf84a,
		[Description("BIMobject")]
		Bimobject = 0xf378,
		[Description("Binoculars")]
		Binoculars = 0xf1e5,
		[Description("Biohazard")]
		Biohazard = 0xf780,
		[Description("Birthday Cake")]
		BirthdayCake = 0xf1fd,
		[Description("Bitbucket")]
		Bitbucket = 0xf171,
		[Description("Bitcoin")]
		Bitcoin = 0xf379,
		[Description("Bity")]
		Bity = 0xf37a,
		[Description("Font Awesome Black Tie")]
		BlackTie = 0xf27e,
		[Description("BlackBerry")]
		Blackberry = 0xf37b,
		[Description("Blender")]
		Blender = 0xf517,
		[Description("Blender Phone")]
		BlenderPhone = 0xf6b6,
		[Description("Blind")]
		Blind = 0xf29d,
		[Description("Blog")]
		Blog = 0xf781,
		[Description("Blogger")]
		Blogger = 0xf37c,
		[Description("Blogger B")]
		BloggerB = 0xf37d,
		[Description("Bluetooth")]
		Bluetooth = 0xf293,
		[Description("Bluetooth")]
		BluetoothB = 0xf294,
		[Description("bold")]
		Bold = 0xf032,
		[Description("Lightning Bolt")]
		Bolt = 0xf0e7,
		[Description("Bomb")]
		Bomb = 0xf1e2,
		[Description("Bone")]
		Bone = 0xf5d7,
		[Description("Bong")]
		Bong = 0xf55c,
		[Description("book")]
		Book = 0xf02d,
		[Description("Book of the Dead")]
		BookDead = 0xf6b7,
		[Description("Medical Book")]
		BookMedical = 0xf7e6,
		[Description("Book Open")]
		BookOpen = 0xf518,
		[Description("Book Reader")]
		BookReader = 0xf5da,
		[Description("bookmark")]
		Bookmark = 0xf02e,
		[Description("Bootstrap")]
		Bootstrap = 0xf836,
		[Description("Border All")]
		BorderAll = 0xf84c,
		[Description("Border None")]
		BorderNone = 0xf850,
		[Description("Border Style")]
		BorderStyle = 0xf853,
		[Description("Bowling Ball")]
		BowlingBall = 0xf436,
		[Description("Box")]
		Box = 0xf466,
		[Description("Box Open")]
		BoxOpen = 0xf49e,
		[Description("Boxes")]
		Boxes = 0xf468,
		[Description("Braille")]
		Braille = 0xf2a1,
		[Description("Brain")]
		Brain = 0xf5dc,
		[Description("Bread Slice")]
		BreadSlice = 0xf7ec,
		[Description("Briefcase")]
		Briefcase = 0xf0b1,
		[Description("Medical Briefcase")]
		BriefcaseMedical = 0xf469,
		[Description("Broadcast Tower")]
		BroadcastTower = 0xf519,
		[Description("Broom")]
		Broom = 0xf51a,
		[Description("Brush")]
		Brush = 0xf55d,
		[Description("BTC")]
		Btc = 0xf15a,
		[Description("Buffer")]
		Buffer = 0xf837,
		[Description("Bug")]
		Bug = 0xf188,
		[Description("Building")]
		Building = 0xf1ad,
		[Description("bullhorn")]
		Bullhorn = 0xf0a1,
		[Description("Bullseye")]
		Bullseye = 0xf140,
		[Description("Burn")]
		Burn = 0xf46a,
		[Description("Büromöbel-Experte GmbH & Co. KG.")]
		Buromobelexperte = 0xf37f,
		[Description("Bus")]
		Bus = 0xf207,
		[Description("Bus Alt")]
		BusAlt = 0xf55e,
		[Description("Business Time")]
		BusinessTime = 0xf64a,
		[Description("Buy n Large")]
		BuyNLarge = 0xf8a6,
		[Description("BuySellAds")]
		Buysellads = 0xf20d,
		[Description("Calculator")]
		Calculator = 0xf1ec,
		[Description("Calendar")]
		Calendar = 0xf133,
		[Description("Alternate Calendar")]
		CalendarAlt = 0xf073,
		[Description("Calendar Check")]
		CalendarCheck = 0xf274,
		[Description("Calendar with Day Focus")]
		CalendarDay = 0xf783,
		[Description("Calendar Minus")]
		CalendarMinus = 0xf272,
		[Description("Calendar Plus")]
		CalendarPlus = 0xf271,
		[Description("Calendar Times")]
		CalendarTimes = 0xf273,
		[Description("Calendar with Week Focus")]
		CalendarWeek = 0xf784,
		[Description("camera")]
		Camera = 0xf030,
		[Description("Retro Camera")]
		CameraRetro = 0xf083,
		[Description("Campground")]
		Campground = 0xf6bb,
		[Description("Canadian Maple Leaf")]
		CanadianMapleLeaf = 0xf785,
		[Description("Candy Cane")]
		CandyCane = 0xf786,
		[Description("Cannabis")]
		Cannabis = 0xf55f,
		[Description("Capsules")]
		Capsules = 0xf46b,
		[Description("Car")]
		Car = 0xf1b9,
		[Description("Alternate Car")]
		CarAlt = 0xf5de,
		[Description("Car Battery")]
		CarBattery = 0xf5df,
		[Description("Car Crash")]
		CarCrash = 0xf5e1,
		[Description("Car Side")]
		CarSide = 0xf5e4,
		[Description("Caravan")]
		Caravan = 0xf8ff,
		[Description("Caret Down")]
		CaretDown = 0xf0d7,
		[Description("Caret Left")]
		CaretLeft = 0xf0d9,
		[Description("Caret Right")]
		CaretRight = 0xf0da,
		[Description("Caret Square Down")]
		CaretSquareDown = 0xf150,
		[Description("Caret Square Left")]
		CaretSquareLeft = 0xf191,
		[Description("Caret Square Right")]
		CaretSquareRight = 0xf152,
		[Description("Caret Square Up")]
		CaretSquareUp = 0xf151,
		[Description("Caret Up")]
		CaretUp = 0xf0d8,
		[Description("Carrot")]
		Carrot = 0xf787,
		[Description("Shopping Cart Arrow Down")]
		CartArrowDown = 0xf218,
		[Description("Add to Shopping Cart")]
		CartPlus = 0xf217,
		[Description("Cash Register")]
		CashRegister = 0xf788,
		[Description("Cat")]
		Cat = 0xf6be,
		[Description("Amazon Pay Credit Card")]
		CcAmazonPay = 0xf42d,
		[Description("American Express Credit Card")]
		CcAmex = 0xf1f3,
		[Description("Apple Pay Credit Card")]
		CcApplePay = 0xf416,
		[Description("Diner's Club Credit Card")]
		CcDinersClub = 0xf24c,
		[Description("Discover Credit Card")]
		CcDiscover = 0xf1f2,
		[Description("JCB Credit Card")]
		CcJcb = 0xf24b,
		[Description("MasterCard Credit Card")]
		CcMastercard = 0xf1f1,
		[Description("Paypal Credit Card")]
		CcPaypal = 0xf1f4,
		[Description("Stripe Credit Card")]
		CcStripe = 0xf1f5,
		[Description("Visa Credit Card")]
		CcVisa = 0xf1f0,
		[Description("Centercode")]
		Centercode = 0xf380,
		[Description("Centos")]
		Centos = 0xf789,
		[Description("certificate")]
		Certificate = 0xf0a3,
		[Description("Chair")]
		Chair = 0xf6c0,
		[Description("Chalkboard")]
		Chalkboard = 0xf51b,
		[Description("Chalkboard Teacher")]
		ChalkboardTeacher = 0xf51c,
		[Description("Charging Station")]
		ChargingStation = 0xf5e7,
		[Description("Area Chart")]
		ChartArea = 0xf1fe,
		[Description("Bar Chart")]
		ChartBar = 0xf080,
		[Description("Line Chart")]
		ChartLine = 0xf201,
		[Description("Pie Chart")]
		ChartPie = 0xf200,
		[Description("Check")]
		Check = 0xf00c,
		[Description("Check Circle")]
		CheckCircle = 0xf058,
		[Description("Double Check")]
		CheckDouble = 0xf560,
		[Description("Check Square")]
		CheckSquare = 0xf14a,
		[Description("Cheese")]
		Cheese = 0xf7ef,
		[Description("Chess")]
		Chess = 0xf439,
		[Description("Chess Bishop")]
		ChessBishop = 0xf43a,
		[Description("Chess Board")]
		ChessBoard = 0xf43c,
		[Description("Chess King")]
		ChessKing = 0xf43f,
		[Description("Chess Knight")]
		ChessKnight = 0xf441,
		[Description("Chess Pawn")]
		ChessPawn = 0xf443,
		[Description("Chess Queen")]
		ChessQueen = 0xf445,
		[Description("Chess Rook")]
		ChessRook = 0xf447,
		[Description("Chevron Circle Down")]
		ChevronCircleDown = 0xf13a,
		[Description("Chevron Circle Left")]
		ChevronCircleLeft = 0xf137,
		[Description("Chevron Circle Right")]
		ChevronCircleRight = 0xf138,
		[Description("Chevron Circle Up")]
		ChevronCircleUp = 0xf139,
		[Description("chevron-down")]
		ChevronDown = 0xf078,
		[Description("chevron-left")]
		ChevronLeft = 0xf053,
		[Description("chevron-right")]
		ChevronRight = 0xf054,
		[Description("chevron-up")]
		ChevronUp = 0xf077,
		[Description("Child")]
		Child = 0xf1ae,
		[Description("Chrome")]
		Chrome = 0xf268,
		[Description("Chromecast")]
		Chromecast = 0xf838,
		[Description("Church")]
		Church = 0xf51d,
		[Description("Circle")]
		Circle = 0xf111,
		[Description("Circle Notched")]
		CircleNotch = 0xf1ce,
		[Description("City")]
		City = 0xf64f,
		[Description("Medical Clinic")]
		ClinicMedical = 0xf7f2,
		[Description("Clipboard")]
		Clipboard = 0xf328,
		[Description("Clipboard with Check")]
		ClipboardCheck = 0xf46c,
		[Description("Clipboard List")]
		ClipboardList = 0xf46d,
		[Description("Clock")]
		Clock = 0xf017,
		[Description("Clone")]
		Clone = 0xf24d,
		[Description("Closed Captioning")]
		ClosedCaptioning = 0xf20a,
		[Description("Cloud")]
		Cloud = 0xf0c2,
		[Description("Alternate Cloud Download")]
		CloudDownloadAlt = 0xf381,
		[Description("Cloud with (a chance of) Meatball")]
		CloudMeatball = 0xf73b,
		[Description("Cloud with Moon")]
		CloudMoon = 0xf6c3,
		[Description("Cloud with Moon and Rain")]
		CloudMoonRain = 0xf73c,
		[Description("Cloud with Rain")]
		CloudRain = 0xf73d,
		[Description("Cloud with Heavy Showers")]
		CloudShowersHeavy = 0xf740,
		[Description("Cloud with Sun")]
		CloudSun = 0xf6c4,
		[Description("Cloud with Sun and Rain")]
		CloudSunRain = 0xf743,
		[Description("Alternate Cloud Upload")]
		CloudUploadAlt = 0xf382,
		[Description("cloudscale.ch")]
		Cloudscale = 0xf383,
		[Description("Cloudsmith")]
		Cloudsmith = 0xf384,
		[Description("cloudversify")]
		Cloudversify = 0xf385,
		[Description("Cocktail")]
		Cocktail = 0xf561,
		[Description("Code")]
		Code = 0xf121,
		[Description("Code Branch")]
		CodeBranch = 0xf126,
		[Description("Codepen")]
		Codepen = 0xf1cb,
		[Description("Codie Pie")]
		Codiepie = 0xf284,
		[Description("Coffee")]
		Coffee = 0xf0f4,
		[Description("cog")]
		Cog = 0xf013,
		[Description("cogs")]
		Cogs = 0xf085,
		[Description("Coins")]
		Coins = 0xf51e,
		[Description("Columns")]
		Columns = 0xf0db,
		[Description("comment")]
		Comment = 0xf075,
		[Description("Alternate Comment")]
		CommentAlt = 0xf27a,
		[Description("Comment Dollar")]
		CommentDollar = 0xf651,
		[Description("Comment Dots")]
		CommentDots = 0xf4ad,
		[Description("Alternate Medical Chat")]
		CommentMedical = 0xf7f5,
		[Description("Comment Slash")]
		CommentSlash = 0xf4b3,
		[Description("comments")]
		Comments = 0xf086,
		[Description("Comments Dollar")]
		CommentsDollar = 0xf653,
		[Description("Compact Disc")]
		CompactDisc = 0xf51f,
		[Description("Compass")]
		Compass = 0xf14e,
		[Description("Compress")]
		Compress = 0xf066,
		[Description("Alternate Compress")]
		CompressAlt = 0xf422,
		[Description("Alternate Compress Arrows")]
		CompressArrowsAlt = 0xf78c,
		[Description("Concierge Bell")]
		ConciergeBell = 0xf562,
		[Description("Confluence")]
		Confluence = 0xf78d,
		[Description("Connect Develop")]
		Connectdevelop = 0xf20e,
		[Description("Contao")]
		Contao = 0xf26d,
		[Description("Cookie")]
		Cookie = 0xf563,
		[Description("Cookie Bite")]
		CookieBite = 0xf564,
		[Description("Copy")]
		Copy = 0xf0c5,
		[Description("Copyright")]
		Copyright = 0xf1f9,
		[Description("Cotton Bureau")]
		CottonBureau = 0xf89e,
		[Description("Couch")]
		Couch = 0xf4b8,
		[Description("cPanel")]
		Cpanel = 0xf388,
		[Description("Creative Commons")]
		CreativeCommons = 0xf25e,
		[Description("Creative Commons Attribution")]
		CreativeCommonsBy = 0xf4e7,
		[Description("Creative Commons Noncommercial")]
		CreativeCommonsNc = 0xf4e8,
		[Description("Creative Commons Noncommercial (Euro Sign)")]
		CreativeCommonsNcEu = 0xf4e9,
		[Description("Creative Commons Noncommercial (Yen Sign)")]
		CreativeCommonsNcJp = 0xf4ea,
		[Description("Creative Commons No Derivative Works")]
		CreativeCommonsNd = 0xf4eb,
		[Description("Creative Commons Public Domain")]
		CreativeCommonsPd = 0xf4ec,
		[Description("Alternate Creative Commons Public Domain")]
		CreativeCommonsPdAlt = 0xf4ed,
		[Description("Creative Commons Remix")]
		CreativeCommonsRemix = 0xf4ee,
		[Description("Creative Commons Share Alike")]
		CreativeCommonsSa = 0xf4ef,
		[Description("Creative Commons Sampling")]
		CreativeCommonsSampling = 0xf4f0,
		[Description("Creative Commons Sampling +")]
		CreativeCommonsSamplingPlus = 0xf4f1,
		[Description("Creative Commons Share")]
		CreativeCommonsShare = 0xf4f2,
		[Description("Creative Commons CC0")]
		CreativeCommonsZero = 0xf4f3,
		[Description("Credit Card")]
		CreditCard = 0xf09d,
		[Description("Critical Role")]
		CriticalRole = 0xf6c9,
		[Description("crop")]
		Crop = 0xf125,
		[Description("Alternate Crop")]
		CropAlt = 0xf565,
		[Description("Cross")]
		Cross = 0xf654,
		[Description("Crosshairs")]
		Crosshairs = 0xf05b,
		[Description("Crow")]
		Crow = 0xf520,
		[Description("Crown")]
		Crown = 0xf521,
		[Description("Crutch")]
		Crutch = 0xf7f7,
		[Description("CSS 3 Logo")]
		Css3 = 0xf13c,
		[Description("Alternate CSS3 Logo")]
		Css3Alt = 0xf38b,
		[Description("Cube")]
		Cube = 0xf1b2,
		[Description("Cubes")]
		Cubes = 0xf1b3,
		[Description("Cut")]
		Cut = 0xf0c4,
		[Description("Cuttlefish")]
		Cuttlefish = 0xf38c,
		[Description("Dungeons & Dragons")]
		DAndD = 0xf38d,
		[Description("D&D Beyond")]
		DAndDBeyond = 0xf6ca,
		[Description("dailymotion")]
		Dailymotion = 0xf952,
		[Description("DashCube")]
		Dashcube = 0xf210,
		[Description("Database")]
		Database = 0xf1c0,
		[Description("Deaf")]
		Deaf = 0xf2a4,
		[Description("Delicious")]
		Delicious = 0xf1a5,
		[Description("Democrat")]
		Democrat = 0xf747,
		[Description("deploy.dog")]
		Deploydog = 0xf38e,
		[Description("Deskpro")]
		Deskpro = 0xf38f,
		[Description("Desktop")]
		Desktop = 0xf108,
		[Description("DEV")]
		Dev = 0xf6cc,
		[Description("deviantART")]
		Deviantart = 0xf1bd,
		[Description("Dharmachakra")]
		Dharmachakra = 0xf655,
		[Description("DHL")]
		Dhl = 0xf790,
		[Description("Diagnoses")]
		Diagnoses = 0xf470,
		[Description("Diaspora")]
		Diaspora = 0xf791,
		[Description("Dice")]
		Dice = 0xf522,
		[Description("Dice D20")]
		DiceD20 = 0xf6cf,
		[Description("Dice D6")]
		DiceD6 = 0xf6d1,
		[Description("Dice Five")]
		DiceFive = 0xf523,
		[Description("Dice Four")]
		DiceFour = 0xf524,
		[Description("Dice One")]
		DiceOne = 0xf525,
		[Description("Dice Six")]
		DiceSix = 0xf526,
		[Description("Dice Three")]
		DiceThree = 0xf527,
		[Description("Dice Two")]
		DiceTwo = 0xf528,
		[Description("Digg Logo")]
		Digg = 0xf1a6,
		[Description("Digital Ocean")]
		DigitalOcean = 0xf391,
		[Description("Digital Tachograph")]
		DigitalTachograph = 0xf566,
		[Description("Directions")]
		Directions = 0xf5eb,
		[Description("Discord")]
		Discord = 0xf392,
		[Description("Discourse")]
		Discourse = 0xf393,
		[Description("Divide")]
		Divide = 0xf529,
		[Description("Dizzy Face")]
		Dizzy = 0xf567,
		[Description("DNA")]
		Dna = 0xf471,
		[Description("DocHub")]
		Dochub = 0xf394,
		[Description("Docker")]
		Docker = 0xf395,
		[Description("Dog")]
		Dog = 0xf6d3,
		[Description("Dollar Sign")]
		DollarSign = 0xf155,
		[Description("Dolly")]
		Dolly = 0xf472,
		[Description("Dolly Flatbed")]
		DollyFlatbed = 0xf474,
		[Description("Donate")]
		Donate = 0xf4b9,
		[Description("Door Closed")]
		DoorClosed = 0xf52a,
		[Description("Door Open")]
		DoorOpen = 0xf52b,
		[Description("Dot Circle")]
		DotCircle = 0xf192,
		[Description("Dove")]
		Dove = 0xf4ba,
		[Description("Download")]
		Download = 0xf019,
		[Description("Draft2digital")]
		Draft2digital = 0xf396,
		[Description("Drafting Compass")]
		DraftingCompass = 0xf568,
		[Description("Dragon")]
		Dragon = 0xf6d5,
		[Description("Draw Polygon")]
		DrawPolygon = 0xf5ee,
		[Description("Dribbble")]
		Dribbble = 0xf17d,
		[Description("Dribbble Square")]
		DribbbleSquare = 0xf397,
		[Description("Dropbox")]
		Dropbox = 0xf16b,
		[Description("Drum")]
		Drum = 0xf569,
		[Description("Drum Steelpan")]
		DrumSteelpan = 0xf56a,
		[Description("Drumstick with Bite Taken Out")]
		DrumstickBite = 0xf6d7,
		[Description("Drupal Logo")]
		Drupal = 0xf1a9,
		[Description("Dumbbell")]
		Dumbbell = 0xf44b,
		[Description("Dumpster")]
		Dumpster = 0xf793,
		[Description("Dumpster Fire")]
		DumpsterFire = 0xf794,
		[Description("Dungeon")]
		Dungeon = 0xf6d9,
		[Description("Dyalog")]
		Dyalog = 0xf399,
		[Description("Earlybirds")]
		Earlybirds = 0xf39a,
		[Description("eBay")]
		Ebay = 0xf4f4,
		[Description("Edge Browser")]
		Edge = 0xf282,
		[Description("Edit")]
		Edit = 0xf044,
		[Description("Egg")]
		Egg = 0xf7fb,
		[Description("eject")]
		Eject = 0xf052,
		[Description("Elementor")]
		Elementor = 0xf430,
		[Description("Horizontal Ellipsis")]
		EllipsisH = 0xf141,
		[Description("Vertical Ellipsis")]
		EllipsisV = 0xf142,
		[Description("Ello")]
		Ello = 0xf5f1,
		[Description("Ember")]
		Ember = 0xf423,
		[Description("Galactic Empire")]
		Empire = 0xf1d1,
		[Description("Envelope")]
		Envelope = 0xf0e0,
		[Description("Envelope Open")]
		EnvelopeOpen = 0xf2b6,
		[Description("Envelope Open-text")]
		EnvelopeOpenText = 0xf658,
		[Description("Envelope Square")]
		EnvelopeSquare = 0xf199,
		[Description("Envira Gallery")]
		Envira = 0xf299,
		[Description("Equals")]
		Equals = 0xf52c,
		[Description("eraser")]
		Eraser = 0xf12d,
		[Description("Erlang")]
		Erlang = 0xf39d,
		[Description("Ethereum")]
		Ethereum = 0xf42e,
		[Description("Ethernet")]
		Ethernet = 0xf796,
		[Description("Etsy")]
		Etsy = 0xf2d7,
		[Description("Euro Sign")]
		EuroSign = 0xf153,
		[Description("Evernote")]
		Evernote = 0xf839,
		[Description("Alternate Exchange")]
		ExchangeAlt = 0xf362,
		[Description("exclamation")]
		Exclamation = 0xf12a,
		[Description("Exclamation Circle")]
		ExclamationCircle = 0xf06a,
		[Description("Exclamation Triangle")]
		ExclamationTriangle = 0xf071,
		[Description("Expand")]
		Expand = 0xf065,
		[Description("Alternate Expand")]
		ExpandAlt = 0xf424,
		[Description("Alternate Expand Arrows")]
		ExpandArrowsAlt = 0xf31e,
		[Description("ExpeditedSSL")]
		Expeditedssl = 0xf23e,
		[Description("Alternate External Link")]
		ExternalLinkAlt = 0xf35d,
		[Description("Alternate External Link Square")]
		ExternalLinkSquareAlt = 0xf360,
		[Description("Eye")]
		Eye = 0xf06e,
		[Description("Eye Dropper")]
		EyeDropper = 0xf1fb,
		[Description("Eye Slash")]
		EyeSlash = 0xf070,
		[Description("Facebook")]
		Facebook = 0xf09a,
		[Description("Facebook F")]
		FacebookF = 0xf39e,
		[Description("Facebook Messenger")]
		FacebookMessenger = 0xf39f,
		[Description("Facebook Square")]
		FacebookSquare = 0xf082,
		[Description("Fan")]
		Fan = 0xf863,
		[Description("Fantasy Flight-games")]
		FantasyFlightGames = 0xf6dc,
		[Description("fast-backward")]
		FastBackward = 0xf049,
		[Description("fast-forward")]
		FastForward = 0xf050,
		[Description("Fax")]
		Fax = 0xf1ac,
		[Description("Feather")]
		Feather = 0xf52d,
		[Description("Alternate Feather")]
		FeatherAlt = 0xf56b,
		[Description("FedEx")]
		Fedex = 0xf797,
		[Description("Fedora")]
		Fedora = 0xf798,
		[Description("Female")]
		Female = 0xf182,
		[Description("fighter-jet")]
		FighterJet = 0xf0fb,
		[Description("Figma")]
		Figma = 0xf799,
		[Description("File")]
		File = 0xf15b,
		[Description("Alternate File")]
		FileAlt = 0xf15c,
		[Description("Archive File")]
		FileArchive = 0xf1c6,
		[Description("Audio File")]
		FileAudio = 0xf1c7,
		[Description("Code File")]
		FileCode = 0xf1c9,
		[Description("File Contract")]
		FileContract = 0xf56c,
		[Description("File CSV")]
		FileCsv = 0xf6dd,
		[Description("File Download")]
		FileDownload = 0xf56d,
		[Description("Excel File")]
		FileExcel = 0xf1c3,
		[Description("File Export")]
		FileExport = 0xf56e,
		[Description("Image File")]
		FileImage = 0xf1c5,
		[Description("File Import")]
		FileImport = 0xf56f,
		[Description("File Invoice")]
		FileInvoice = 0xf570,
		[Description("File Invoice with US Dollar")]
		FileInvoiceDollar = 0xf571,
		[Description("Medical File")]
		FileMedical = 0xf477,
		[Description("Alternate Medical File")]
		FileMedicalAlt = 0xf478,
		[Description("PDF File")]
		FilePdf = 0xf1c1,
		[Description("Powerpoint File")]
		FilePowerpoint = 0xf1c4,
		[Description("File Prescription")]
		FilePrescription = 0xf572,
		[Description("File Signature")]
		FileSignature = 0xf573,
		[Description("File Upload")]
		FileUpload = 0xf574,
		[Description("Video File")]
		FileVideo = 0xf1c8,
		[Description("Word File")]
		FileWord = 0xf1c2,
		[Description("Fill")]
		Fill = 0xf575,
		[Description("Fill Drip")]
		FillDrip = 0xf576,
		[Description("Film")]
		Film = 0xf008,
		[Description("Filter")]
		Filter = 0xf0b0,
		[Description("Fingerprint")]
		Fingerprint = 0xf577,
		[Description("fire")]
		Fire = 0xf06d,
		[Description("Alternate Fire")]
		FireAlt = 0xf7e4,
		[Description("fire-extinguisher")]
		FireExtinguisher = 0xf134,
		[Description("Firefox")]
		Firefox = 0xf269,
		[Description("Firefox Browser")]
		FirefoxBrowser = 0xf907,
		[Description("First Aid")]
		FirstAid = 0xf479,
		[Description("First Order")]
		FirstOrder = 0xf2b0,
		[Description("Alternate First Order")]
		FirstOrderAlt = 0xf50a,
		[Description("firstdraft")]
		Firstdraft = 0xf3a1,
		[Description("Fish")]
		Fish = 0xf578,
		[Description("Raised Fist")]
		FistRaised = 0xf6de,
		[Description("flag")]
		Flag = 0xf024,
		[Description("flag-checkered")]
		FlagCheckered = 0xf11e,
		[Description("United States of America Flag")]
		FlagUsa = 0xf74d,
		[Description("Flask")]
		Flask = 0xf0c3,
		[Description("Flickr")]
		Flickr = 0xf16e,
		[Description("Flipboard")]
		Flipboard = 0xf44d,
		[Description("Flushed Face")]
		Flushed = 0xf579,
		[Description("Fly")]
		Fly = 0xf417,
		[Description("Folder")]
		Folder = 0xf07b,
		[Description("Folder Minus")]
		FolderMinus = 0xf65d,
		[Description("Folder Open")]
		FolderOpen = 0xf07c,
		[Description("Folder Plus")]
		FolderPlus = 0xf65e,
		[Description("font")]
		Font = 0xf031,
		[Description("Font Awesome")]
		FontAwesome = 0xf2b4,
		[Description("Alternate Font Awesome")]
		FontAwesomeAlt = 0xf35c,
		[Description("Font Awesome Flag")]
		FontAwesomeFlag = 0xf425,
		[Description("Font Awesome Full Logo")]
		FontAwesomeLogoFull = 0xf4e6,
		[Description("Fonticons")]
		Fonticons = 0xf280,
		[Description("Fonticons Fi")]
		FonticonsFi = 0xf3a2,
		[Description("Football Ball")]
		FootballBall = 0xf44e,
		[Description("Fort Awesome")]
		FortAwesome = 0xf286,
		[Description("Alternate Fort Awesome")]
		FortAwesomeAlt = 0xf3a3,
		[Description("Forumbee")]
		Forumbee = 0xf211,
		[Description("forward")]
		Forward = 0xf04e,
		[Description("Foursquare")]
		Foursquare = 0xf180,
		[Description("freeCodeCamp")]
		FreeCodeCamp = 0xf2c5,
		[Description("FreeBSD")]
		Freebsd = 0xf3a4,
		[Description("Frog")]
		Frog = 0xf52e,
		[Description("Frowning Face")]
		Frown = 0xf119,
		[Description("Frowning Face With Open Mouth")]
		FrownOpen = 0xf57a,
		[Description("Fulcrum")]
		Fulcrum = 0xf50b,
		[Description("Funnel Dollar")]
		FunnelDollar = 0xf662,
		[Description("Futbol")]
		Futbol = 0xf1e3,
		[Description("Galactic Republic")]
		GalacticRepublic = 0xf50c,
		[Description("Galactic Senate")]
		GalacticSenate = 0xf50d,
		[Description("Gamepad")]
		Gamepad = 0xf11b,
		[Description("Gas Pump")]
		GasPump = 0xf52f,
		[Description("Gavel")]
		Gavel = 0xf0e3,
		[Description("Gem")]
		Gem = 0xf3a5,
		[Description("Genderless")]
		Genderless = 0xf22d,
		[Description("Get Pocket")]
		GetPocket = 0xf265,
		[Description("GG Currency")]
		Gg = 0xf260,
		[Description("GG Currency Circle")]
		GgCircle = 0xf261,
		[Description("Ghost")]
		Ghost = 0xf6e2,
		[Description("gift")]
		Gift = 0xf06b,
		[Description("Gifts")]
		Gifts = 0xf79c,
		[Description("Git")]
		Git = 0xf1d3,
		[Description("Git Alt")]
		GitAlt = 0xf841,
		[Description("Git Square")]
		GitSquare = 0xf1d2,
		[Description("GitHub")]
		Github = 0xf09b,
		[Description("Alternate GitHub")]
		GithubAlt = 0xf113,
		[Description("GitHub Square")]
		GithubSquare = 0xf092,
		[Description("GitKraken")]
		Gitkraken = 0xf3a6,
		[Description("GitLab")]
		Gitlab = 0xf296,
		[Description("Gitter")]
		Gitter = 0xf426,
		[Description("Glass Cheers")]
		GlassCheers = 0xf79f,
		[Description("Martini Glass")]
		GlassMartini = 0xf000,
		[Description("Alternate Glass Martini")]
		GlassMartiniAlt = 0xf57b,
		[Description("Glass Whiskey")]
		GlassWhiskey = 0xf7a0,
		[Description("Glasses")]
		Glasses = 0xf530,
		[Description("Glide")]
		Glide = 0xf2a5,
		[Description("Glide G")]
		GlideG = 0xf2a6,
		[Description("Globe")]
		Globe = 0xf0ac,
		[Description("Globe with Africa shown")]
		GlobeAfrica = 0xf57c,
		[Description("Globe with Americas shown")]
		GlobeAmericas = 0xf57d,
		[Description("Globe with Asia shown")]
		GlobeAsia = 0xf57e,
		[Description("Globe with Europe shown")]
		GlobeEurope = 0xf7a2,
		[Description("Gofore")]
		Gofore = 0xf3a7,
		[Description("Golf Ball")]
		GolfBall = 0xf450,
		[Description("Goodreads")]
		Goodreads = 0xf3a8,
		[Description("Goodreads G")]
		GoodreadsG = 0xf3a9,
		[Description("Google Logo")]
		Google = 0xf1a0,
		[Description("Google Drive")]
		GoogleDrive = 0xf3aa,
		[Description("Google Play")]
		GooglePlay = 0xf3ab,
		[Description("Google Plus")]
		GooglePlus = 0xf2b3,
		[Description("Google Plus G")]
		GooglePlusG = 0xf0d5,
		[Description("Google Plus Square")]
		GooglePlusSquare = 0xf0d4,
		[Description("Google Wallet")]
		GoogleWallet = 0xf1ee,
		[Description("Gopuram")]
		Gopuram = 0xf664,
		[Description("Graduation Cap")]
		GraduationCap = 0xf19d,
		[Description("Gratipay (Gittip)")]
		Gratipay = 0xf184,
		[Description("Grav")]
		Grav = 0xf2d6,
		[Description("Greater Than")]
		GreaterThan = 0xf531,
		[Description("Greater Than Equal To")]
		GreaterThanEqual = 0xf532,
		[Description("Grimacing Face")]
		Grimace = 0xf57f,
		[Description("Grinning Face")]
		Grin = 0xf580,
		[Description("Alternate Grinning Face")]
		GrinAlt = 0xf581,
		[Description("Grinning Face With Smiling Eyes")]
		GrinBeam = 0xf582,
		[Description("Grinning Face With Sweat")]
		GrinBeamSweat = 0xf583,
		[Description("Smiling Face With Heart-Eyes")]
		GrinHearts = 0xf584,
		[Description("Grinning Squinting Face")]
		GrinSquint = 0xf585,
		[Description("Rolling on the Floor Laughing")]
		GrinSquintTears = 0xf586,
		[Description("Star-Struck")]
		GrinStars = 0xf587,
		[Description("Face With Tears of Joy")]
		GrinTears = 0xf588,
		[Description("Face With Tongue")]
		GrinTongue = 0xf589,
		[Description("Squinting Face With Tongue")]
		GrinTongueSquint = 0xf58a,
		[Description("Winking Face With Tongue")]
		GrinTongueWink = 0xf58b,
		[Description("Grinning Winking Face")]
		GrinWink = 0xf58c,
		[Description("Grip Horizontal")]
		GripHorizontal = 0xf58d,
		[Description("Grip Lines")]
		GripLines = 0xf7a4,
		[Description("Grip Lines Vertical")]
		GripLinesVertical = 0xf7a5,
		[Description("Grip Vertical")]
		GripVertical = 0xf58e,
		[Description("Gripfire, Inc.")]
		Gripfire = 0xf3ac,
		[Description("Grunt")]
		Grunt = 0xf3ad,
		[Description("Guitar")]
		Guitar = 0xf7a6,
		[Description("Gulp")]
		Gulp = 0xf3ae,
		[Description("H Square")]
		HSquare = 0xf0fd,
		[Description("Hacker News")]
		HackerNews = 0xf1d4,
		[Description("Hacker News Square")]
		HackerNewsSquare = 0xf3af,
		[Description("Hackerrank")]
		Hackerrank = 0xf5f7,
		[Description("Hamburger")]
		Hamburger = 0xf805,
		[Description("Hammer")]
		Hammer = 0xf6e3,
		[Description("Hamsa")]
		Hamsa = 0xf665,
		[Description("Hand Holding")]
		HandHolding = 0xf4bd,
		[Description("Hand Holding Heart")]
		HandHoldingHeart = 0xf4be,
		[Description("Hand Holding US Dollar")]
		HandHoldingUsd = 0xf4c0,
		[Description("Lizard (Hand)")]
		HandLizard = 0xf258,
		[Description("Hand with Middle Finger Raised")]
		HandMiddleFinger = 0xf806,
		[Description("Paper (Hand)")]
		HandPaper = 0xf256,
		[Description("Peace (Hand)")]
		HandPeace = 0xf25b,
		[Description("Hand Pointing Down")]
		HandPointDown = 0xf0a7,
		[Description("Hand Pointing Left")]
		HandPointLeft = 0xf0a5,
		[Description("Hand Pointing Right")]
		HandPointRight = 0xf0a4,
		[Description("Hand Pointing Up")]
		HandPointUp = 0xf0a6,
		[Description("Pointer (Hand)")]
		HandPointer = 0xf25a,
		[Description("Rock (Hand)")]
		HandRock = 0xf255,
		[Description("Scissors (Hand)")]
		HandScissors = 0xf257,
		[Description("Spock (Hand)")]
		HandSpock = 0xf259,
		[Description("Hands")]
		Hands = 0xf4c2,
		[Description("Helping Hands")]
		HandsHelping = 0xf4c4,
		[Description("Handshake")]
		Handshake = 0xf2b5,
		[Description("Hanukiah")]
		Hanukiah = 0xf6e6,
		[Description("Hard Hat")]
		HardHat = 0xf807,
		[Description("Hashtag")]
		Hashtag = 0xf292,
		[Description("Cowboy Hat")]
		HatCowboy = 0xf8c0,
		[Description("Cowboy Hat Side")]
		HatCowboySide = 0xf8c1,
		[Description("Wizard's Hat")]
		HatWizard = 0xf6e8,
		[Description("HDD")]
		Hdd = 0xf0a0,
		[Description("heading")]
		Heading = 0xf1dc,
		[Description("headphones")]
		Headphones = 0xf025,
		[Description("Alternate Headphones")]
		HeadphonesAlt = 0xf58f,
		[Description("Headset")]
		Headset = 0xf590,
		[Description("Heart")]
		Heart = 0xf004,
		[Description("Heart Broken")]
		HeartBroken = 0xf7a9,
		[Description("Heartbeat")]
		Heartbeat = 0xf21e,
		[Description("Helicopter")]
		Helicopter = 0xf533,
		[Description("Highlighter")]
		Highlighter = 0xf591,
		[Description("Hiking")]
		Hiking = 0xf6ec,
		[Description("Hippo")]
		Hippo = 0xf6ed,
		[Description("Hips")]
		Hips = 0xf452,
		[Description("HireAHelper")]
		HireAHelper = 0xf3b0,
		[Description("History")]
		History = 0xf1da,
		[Description("Hockey Puck")]
		HockeyPuck = 0xf453,
		[Description("Holly Berry")]
		HollyBerry = 0xf7aa,
		[Description("home")]
		Home = 0xf015,
		[Description("Hooli")]
		Hooli = 0xf427,
		[Description("Hornbill")]
		Hornbill = 0xf592,
		[Description("Horse")]
		Horse = 0xf6f0,
		[Description("Horse Head")]
		HorseHead = 0xf7ab,
		[Description("hospital")]
		Hospital = 0xf0f8,
		[Description("Alternate Hospital")]
		HospitalAlt = 0xf47d,
		[Description("Hospital Symbol")]
		HospitalSymbol = 0xf47e,
		[Description("Hot Tub")]
		HotTub = 0xf593,
		[Description("Hot Dog")]
		Hotdog = 0xf80f,
		[Description("Hotel")]
		Hotel = 0xf594,
		[Description("Hotjar")]
		Hotjar = 0xf3b1,
		[Description("Hourglass")]
		Hourglass = 0xf254,
		[Description("Hourglass End")]
		HourglassEnd = 0xf253,
		[Description("Hourglass Half")]
		HourglassHalf = 0xf252,
		[Description("Hourglass Start")]
		HourglassStart = 0xf251,
		[Description("Damaged House")]
		HouseDamage = 0xf6f1,
		[Description("Houzz")]
		Houzz = 0xf27c,
		[Description("Hryvnia")]
		Hryvnia = 0xf6f2,
		[Description("HTML 5 Logo")]
		Html5 = 0xf13b,
		[Description("HubSpot")]
		Hubspot = 0xf3b2,
		[Description("I Beam Cursor")]
		ICursor = 0xf246,
		[Description("Ice Cream")]
		IceCream = 0xf810,
		[Description("Icicles")]
		Icicles = 0xf7ad,
		[Description("Icons")]
		Icons = 0xf86d,
		[Description("Identification Badge")]
		IdBadge = 0xf2c1,
		[Description("Identification Card")]
		IdCard = 0xf2c2,
		[Description("Alternate Identification Card")]
		IdCardAlt = 0xf47f,
		[Description("iDeal")]
		Ideal = 0xf913,
		[Description("Igloo")]
		Igloo = 0xf7ae,
		[Description("Image")]
		Image = 0xf03e,
		[Description("Images")]
		Images = 0xf302,
		[Description("IMDB")]
		Imdb = 0xf2d8,
		[Description("inbox")]
		Inbox = 0xf01c,
		[Description("Indent")]
		Indent = 0xf03c,
		[Description("Industry")]
		Industry = 0xf275,
		[Description("Infinity")]
		Infinity = 0xf534,
		[Description("Info")]
		Info = 0xf129,
		[Description("Info Circle")]
		InfoCircle = 0xf05a,
		[Description("Instagram")]
		Instagram = 0xf16d,
		[Description("Instagram Square")]
		InstagramSquare = 0xf955,
		[Description("Intercom")]
		Intercom = 0xf7af,
		[Description("Internet-explorer")]
		InternetExplorer = 0xf26b,
		[Description("InVision")]
		Invision = 0xf7b0,
		[Description("ioxhost")]
		Ioxhost = 0xf208,
		[Description("italic")]
		Italic = 0xf033,
		[Description("itch.io")]
		ItchIo = 0xf83a,
		[Description("iTunes")]
		Itunes = 0xf3b4,
		[Description("Itunes Note")]
		ItunesNote = 0xf3b5,
		[Description("Java")]
		Java = 0xf4e4,
		[Description("Jedi")]
		Jedi = 0xf669,
		[Description("Jedi Order")]
		JediOrder = 0xf50e,
		[Description("Jenkis")]
		Jenkins = 0xf3b6,
		[Description("Jira")]
		Jira = 0xf7b1,
		[Description("Joget")]
		Joget = 0xf3b7,
		[Description("Joint")]
		Joint = 0xf595,
		[Description("Joomla Logo")]
		Joomla = 0xf1aa,
		[Description("Journal of the Whills")]
		JournalWhills = 0xf66a,
		[Description("JavaScript (JS)")]
		Js = 0xf3b8,
		[Description("JavaScript (JS) Square")]
		JsSquare = 0xf3b9,
		[Description("jsFiddle")]
		Jsfiddle = 0xf1cc,
		[Description("Kaaba")]
		Kaaba = 0xf66b,
		[Description("Kaggle")]
		Kaggle = 0xf5fa,
		[Description("key")]
		Key = 0xf084,
		[Description("Keybase")]
		Keybase = 0xf4f5,
		[Description("Keyboard")]
		Keyboard = 0xf11c,
		[Description("KeyCDN")]
		Keycdn = 0xf3ba,
		[Description("Khanda")]
		Khanda = 0xf66d,
		[Description("Kickstarter")]
		Kickstarter = 0xf3bb,
		[Description("Kickstarter K")]
		KickstarterK = 0xf3bc,
		[Description("Kissing Face")]
		Kiss = 0xf596,
		[Description("Kissing Face With Smiling Eyes")]
		KissBeam = 0xf597,
		[Description("Face Blowing a Kiss")]
		KissWinkHeart = 0xf598,
		[Description("Kiwi Bird")]
		KiwiBird = 0xf535,
		[Description("KORVUE")]
		Korvue = 0xf42f,
		[Description("Landmark")]
		Landmark = 0xf66f,
		[Description("Language")]
		Language = 0xf1ab,
		[Description("Laptop")]
		Laptop = 0xf109,
		[Description("Laptop Code")]
		LaptopCode = 0xf5fc,
		[Description("Laptop Medical")]
		LaptopMedical = 0xf812,
		[Description("Laravel")]
		Laravel = 0xf3bd,
		[Description("last.fm")]
		Lastfm = 0xf202,
		[Description("last.fm Square")]
		LastfmSquare = 0xf203,
		[Description("Grinning Face With Big Eyes")]
		Laugh = 0xf599,
		[Description("Laugh Face with Beaming Eyes")]
		LaughBeam = 0xf59a,
		[Description("Laughing Squinting Face")]
		LaughSquint = 0xf59b,
		[Description("Laughing Winking Face")]
		LaughWink = 0xf59c,
		[Description("Layer Group")]
		LayerGroup = 0xf5fd,
		[Description("leaf")]
		Leaf = 0xf06c,
		[Description("Leanpub")]
		Leanpub = 0xf212,
		[Description("Lemon")]
		Lemon = 0xf094,
		[Description("Less")]
		Less = 0xf41d,
		[Description("Less Than")]
		LessThan = 0xf536,
		[Description("Less Than Equal To")]
		LessThanEqual = 0xf537,
		[Description("Alternate Level Down")]
		LevelDownAlt = 0xf3be,
		[Description("Alternate Level Up")]
		LevelUpAlt = 0xf3bf,
		[Description("Life Ring")]
		LifeRing = 0xf1cd,
		[Description("Lightbulb")]
		Lightbulb = 0xf0eb,
		[Description("Line")]
		Line = 0xf3c0,
		[Description("Link")]
		Link = 0xf0c1,
		[Description("LinkedIn")]
		Linkedin = 0xf08c,
		[Description("LinkedIn In")]
		LinkedinIn = 0xf0e1,
		[Description("Linode")]
		Linode = 0xf2b8,
		[Description("Linux")]
		Linux = 0xf17c,
		[Description("Turkish Lira Sign")]
		LiraSign = 0xf195,
		[Description("List")]
		List = 0xf03a,
		[Description("Alternate List")]
		ListAlt = 0xf022,
		[Description("list-ol")]
		ListOl = 0xf0cb,
		[Description("list-ul")]
		ListUl = 0xf0ca,
		[Description("location-arrow")]
		LocationArrow = 0xf124,
		[Description("lock")]
		Lock = 0xf023,
		[Description("Lock Open")]
		LockOpen = 0xf3c1,
		[Description("Alternate Long Arrow Down")]
		LongArrowAltDown = 0xf309,
		[Description("Alternate Long Arrow Left")]
		LongArrowAltLeft = 0xf30a,
		[Description("Alternate Long Arrow Right")]
		LongArrowAltRight = 0xf30b,
		[Description("Alternate Long Arrow Up")]
		LongArrowAltUp = 0xf30c,
		[Description("Low Vision")]
		LowVision = 0xf2a8,
		[Description("Luggage Cart")]
		LuggageCart = 0xf59d,
		[Description("lyft")]
		Lyft = 0xf3c3,
		[Description("Magento")]
		Magento = 0xf3c4,
		[Description("magic")]
		Magic = 0xf0d0,
		[Description("magnet")]
		Magnet = 0xf076,
		[Description("Mail Bulk")]
		MailBulk = 0xf674,
		[Description("Mailchimp")]
		Mailchimp = 0xf59e,
		[Description("Male")]
		Male = 0xf183,
		[Description("Mandalorian")]
		Mandalorian = 0xf50f,
		[Description("Map")]
		Map = 0xf279,
		[Description("Map Marked")]
		MapMarked = 0xf59f,
		[Description("Alternate Map Marked")]
		MapMarkedAlt = 0xf5a0,
		[Description("map-marker")]
		MapMarker = 0xf041,
		[Description("Alternate Map Marker")]
		MapMarkerAlt = 0xf3c5,
		[Description("Map Pin")]
		MapPin = 0xf276,
		[Description("Map Signs")]
		MapSigns = 0xf277,
		[Description("Markdown")]
		Markdown = 0xf60f,
		[Description("Marker")]
		Marker = 0xf5a1,
		[Description("Mars")]
		Mars = 0xf222,
		[Description("Mars Double")]
		MarsDouble = 0xf227,
		[Description("Mars Stroke")]
		MarsStroke = 0xf229,
		[Description("Mars Stroke Horizontal")]
		MarsStrokeH = 0xf22b,
		[Description("Mars Stroke Vertical")]
		MarsStrokeV = 0xf22a,
		[Description("Mask")]
		Mask = 0xf6fa,
		[Description("Mastodon")]
		Mastodon = 0xf4f6,
		[Description("MaxCDN")]
		Maxcdn = 0xf136,
		[Description("Material Design for Bootstrap")]
		Mdb = 0xf8ca,
		[Description("Medal")]
		Medal = 0xf5a2,
		[Description("MedApps")]
		Medapps = 0xf3c6,
		[Description("Medium")]
		Medium = 0xf23a,
		[Description("Medium M")]
		MediumM = 0xf3c7,
		[Description("medkit")]
		Medkit = 0xf0fa,
		[Description("MRT")]
		Medrt = 0xf3c8,
		[Description("Meetup")]
		Meetup = 0xf2e0,
		[Description("Megaport")]
		Megaport = 0xf5a3,
		[Description("Neutral Face")]
		Meh = 0xf11a,
		[Description("Face Without Mouth")]
		MehBlank = 0xf5a4,
		[Description("Face With Rolling Eyes")]
		MehRollingEyes = 0xf5a5,
		[Description("Memory")]
		Memory = 0xf538,
		[Description("Mendeley")]
		Mendeley = 0xf7b3,
		[Description("Menorah")]
		Menorah = 0xf676,
		[Description("Mercury")]
		Mercury = 0xf223,
		[Description("Meteor")]
		Meteor = 0xf753,
		[Description("Micro.blog")]
		Microblog = 0xf91a,
		[Description("Microchip")]
		Microchip = 0xf2db,
		[Description("microphone")]
		Microphone = 0xf130,
		[Description("Alternate Microphone")]
		MicrophoneAlt = 0xf3c9,
		[Description("Alternate Microphone Slash")]
		MicrophoneAltSlash = 0xf539,
		[Description("Microphone Slash")]
		MicrophoneSlash = 0xf131,
		[Description("Microscope")]
		Microscope = 0xf610,
		[Description("Microsoft")]
		Microsoft = 0xf3ca,
		[Description("minus")]
		Minus = 0xf068,
		[Description("Minus Circle")]
		MinusCircle = 0xf056,
		[Description("Minus Square")]
		MinusSquare = 0xf146,
		[Description("Mitten")]
		Mitten = 0xf7b5,
		[Description("Mix")]
		Mix = 0xf3cb,
		[Description("Mixcloud")]
		Mixcloud = 0xf289,
		[Description("Mixer")]
		Mixer = 0xf956,
		[Description("Mizuni")]
		Mizuni = 0xf3cc,
		[Description("Mobile Phone")]
		Mobile = 0xf10b,
		[Description("Alternate Mobile")]
		MobileAlt = 0xf3cd,
		[Description("MODX")]
		Modx = 0xf285,
		[Description("Monero")]
		Monero = 0xf3d0,
		[Description("Money Bill")]
		MoneyBill = 0xf0d6,
		[Description("Alternate Money Bill")]
		MoneyBillAlt = 0xf3d1,
		[Description("Wavy Money Bill")]
		MoneyBillWave = 0xf53a,
		[Description("Alternate Wavy Money Bill")]
		MoneyBillWaveAlt = 0xf53b,
		[Description("Money Check")]
		MoneyCheck = 0xf53c,
		[Description("Alternate Money Check")]
		MoneyCheckAlt = 0xf53d,
		[Description("Monument")]
		Monument = 0xf5a6,
		[Description("Moon")]
		Moon = 0xf186,
		[Description("Mortar Pestle")]
		MortarPestle = 0xf5a7,
		[Description("Mosque")]
		Mosque = 0xf678,
		[Description("Motorcycle")]
		Motorcycle = 0xf21c,
		[Description("Mountain")]
		Mountain = 0xf6fc,
		[Description("Mouse")]
		Mouse = 0xf8cc,
		[Description("Mouse Pointer")]
		MousePointer = 0xf245,
		[Description("Mug Hot")]
		MugHot = 0xf7b6,
		[Description("Music")]
		Music = 0xf001,
		[Description("Napster")]
		Napster = 0xf3d2,
		[Description("Neos")]
		Neos = 0xf612,
		[Description("Wired Network")]
		NetworkWired = 0xf6ff,
		[Description("Neuter")]
		Neuter = 0xf22c,
		[Description("Newspaper")]
		Newspaper = 0xf1ea,
		[Description("Nimblr")]
		Nimblr = 0xf5a8,
		[Description("Node.js")]
		Node = 0xf419,
		[Description("Node.js JS")]
		NodeJs = 0xf3d3,
		[Description("Not Equal")]
		NotEqual = 0xf53e,
		[Description("Medical Notes")]
		NotesMedical = 0xf481,
		[Description("npm")]
		Npm = 0xf3d4,
		[Description("NS8")]
		Ns8 = 0xf3d5,
		[Description("Nutritionix")]
		Nutritionix = 0xf3d6,
		[Description("Object Group")]
		ObjectGroup = 0xf247,
		[Description("Object Ungroup")]
		ObjectUngroup = 0xf248,
		[Description("Odnoklassniki")]
		Odnoklassniki = 0xf263,
		[Description("Odnoklassniki Square")]
		OdnoklassnikiSquare = 0xf264,
		[Description("Oil Can")]
		OilCan = 0xf613,
		[Description("Old Republic")]
		OldRepublic = 0xf510,
		[Description("Om")]
		Om = 0xf679,
		[Description("OpenCart")]
		Opencart = 0xf23d,
		[Description("OpenID")]
		Openid = 0xf19b,
		[Description("Opera")]
		Opera = 0xf26a,
		[Description("Optin Monster")]
		OptinMonster = 0xf23c,
		[Description("ORCID")]
		Orcid = 0xf8d2,
		[Description("Open Source Initiative")]
		Osi = 0xf41a,
		[Description("Otter")]
		Otter = 0xf700,
		[Description("Outdent")]
		Outdent = 0xf03b,
		[Description("page4 Corporation")]
		Page4 = 0xf3d7,
		[Description("Pagelines")]
		Pagelines = 0xf18c,
		[Description("Pager")]
		Pager = 0xf815,
		[Description("Paint Brush")]
		PaintBrush = 0xf1fc,
		[Description("Paint Roller")]
		PaintRoller = 0xf5aa,
		[Description("Palette")]
		Palette = 0xf53f,
		[Description("Palfed")]
		Palfed = 0xf3d8,
		[Description("Pallet")]
		Pallet = 0xf482,
		[Description("Paper Plane")]
		PaperPlane = 0xf1d8,
		[Description("Paperclip")]
		Paperclip = 0xf0c6,
		[Description("Parachute Box")]
		ParachuteBox = 0xf4cd,
		[Description("paragraph")]
		Paragraph = 0xf1dd,
		[Description("Parking")]
		Parking = 0xf540,
		[Description("Passport")]
		Passport = 0xf5ab,
		[Description("Pastafarianism")]
		Pastafarianism = 0xf67b,
		[Description("Paste")]
		Paste = 0xf0ea,
		[Description("Patreon")]
		Patreon = 0xf3d9,
		[Description("pause")]
		Pause = 0xf04c,
		[Description("Pause Circle")]
		PauseCircle = 0xf28b,
		[Description("Paw")]
		Paw = 0xf1b0,
		[Description("Paypal")]
		Paypal = 0xf1ed,
		[Description("Peace")]
		Peace = 0xf67c,
		[Description("Pen")]
		Pen = 0xf304,
		[Description("Alternate Pen")]
		PenAlt = 0xf305,
		[Description("Pen Fancy")]
		PenFancy = 0xf5ac,
		[Description("Pen Nib")]
		PenNib = 0xf5ad,
		[Description("Pen Square")]
		PenSquare = 0xf14b,
		[Description("Alternate Pencil")]
		PencilAlt = 0xf303,
		[Description("Pencil Ruler")]
		PencilRuler = 0xf5ae,
		[Description("Penny Arcade")]
		PennyArcade = 0xf704,
		[Description("People Carry")]
		PeopleCarry = 0xf4ce,
		[Description("Hot Pepper")]
		PepperHot = 0xf816,
		[Description("Percent")]
		Percent = 0xf295,
		[Description("Percentage")]
		Percentage = 0xf541,
		[Description("Periscope")]
		Periscope = 0xf3da,
		[Description("Person Entering Booth")]
		PersonBooth = 0xf756,
		[Description("Phabricator")]
		Phabricator = 0xf3db,
		[Description("Phoenix Framework")]
		PhoenixFramework = 0xf3dc,
		[Description("Phoenix Squadron")]
		PhoenixSquadron = 0xf511,
		[Description("Phone")]
		Phone = 0xf095,
		[Description("Alternate Phone")]
		PhoneAlt = 0xf879,
		[Description("Phone Slash")]
		PhoneSlash = 0xf3dd,
		[Description("Phone Square")]
		PhoneSquare = 0xf098,
		[Description("Alternate Phone Square")]
		PhoneSquareAlt = 0xf87b,
		[Description("Phone Volume")]
		PhoneVolume = 0xf2a0,
		[Description("Photo Video")]
		PhotoVideo = 0xf87c,
		[Description("PHP")]
		Php = 0xf457,
		[Description("Pied Piper Logo")]
		PiedPiper = 0xf2ae,
		[Description("Alternate Pied Piper Logo (Old)")]
		PiedPiperAlt = 0xf1a8,
		[Description("Pied Piper Hat (Old)")]
		PiedPiperHat = 0xf4e5,
		[Description("Pied Piper PP Logo (Old)")]
		PiedPiperPp = 0xf1a7,
		[Description("Pied Piper Square Logo (Old)")]
		PiedPiperSquare = 0xf91e,
		[Description("Piggy Bank")]
		PiggyBank = 0xf4d3,
		[Description("Pills")]
		Pills = 0xf484,
		[Description("Pinterest")]
		Pinterest = 0xf0d2,
		[Description("Pinterest P")]
		PinterestP = 0xf231,
		[Description("Pinterest Square")]
		PinterestSquare = 0xf0d3,
		[Description("Pizza Slice")]
		PizzaSlice = 0xf818,
		[Description("Place of Worship")]
		PlaceOfWorship = 0xf67f,
		[Description("plane")]
		Plane = 0xf072,
		[Description("Plane Arrival")]
		PlaneArrival = 0xf5af,
		[Description("Plane Departure")]
		PlaneDeparture = 0xf5b0,
		[Description("play")]
		Play = 0xf04b,
		[Description("Play Circle")]
		PlayCircle = 0xf144,
		[Description("PlayStation")]
		Playstation = 0xf3df,
		[Description("Plug")]
		Plug = 0xf1e6,
		[Description("plus")]
		Plus = 0xf067,
		[Description("Plus Circle")]
		PlusCircle = 0xf055,
		[Description("Plus Square")]
		PlusSquare = 0xf0fe,
		[Description("Podcast")]
		Podcast = 0xf2ce,
		[Description("Poll")]
		Poll = 0xf681,
		[Description("Poll H")]
		PollH = 0xf682,
		[Description("Poo")]
		Poo = 0xf2fe,
		[Description("Poo Storm")]
		PooStorm = 0xf75a,
		[Description("Poop")]
		Poop = 0xf619,
		[Description("Portrait")]
		Portrait = 0xf3e0,
		[Description("Pound Sign")]
		PoundSign = 0xf154,
		[Description("Power Off")]
		PowerOff = 0xf011,
		[Description("Pray")]
		Pray = 0xf683,
		[Description("Praying Hands")]
		PrayingHands = 0xf684,
		[Description("Prescription")]
		Prescription = 0xf5b1,
		[Description("Prescription Bottle")]
		PrescriptionBottle = 0xf485,
		[Description("Alternate Prescription Bottle")]
		PrescriptionBottleAlt = 0xf486,
		[Description("print")]
		Print = 0xf02f,
		[Description("Procedures")]
		Procedures = 0xf487,
		[Description("Product Hunt")]
		ProductHunt = 0xf288,
		[Description("Project Diagram")]
		ProjectDiagram = 0xf542,
		[Description("Pushed")]
		Pushed = 0xf3e1,
		[Description("Puzzle Piece")]
		PuzzlePiece = 0xf12e,
		[Description("Python")]
		Python = 0xf3e2,
		[Description("QQ")]
		Qq = 0xf1d6,
		[Description("qrcode")]
		Qrcode = 0xf029,
		[Description("Question")]
		Question = 0xf128,
		[Description("Question Circle")]
		QuestionCircle = 0xf059,
		[Description("Quidditch")]
		Quidditch = 0xf458,
		[Description("QuinScape")]
		Quinscape = 0xf459,
		[Description("Quora")]
		Quora = 0xf2c4,
		[Description("quote-left")]
		QuoteLeft = 0xf10d,
		[Description("quote-right")]
		QuoteRight = 0xf10e,
		[Description("Quran")]
		Quran = 0xf687,
		[Description("R Project")]
		RProject = 0xf4f7,
		[Description("Radiation")]
		Radiation = 0xf7b9,
		[Description("Alternate Radiation")]
		RadiationAlt = 0xf7ba,
		[Description("Rainbow")]
		Rainbow = 0xf75b,
		[Description("random")]
		Random = 0xf074,
		[Description("Raspberry Pi")]
		RaspberryPi = 0xf7bb,
		[Description("Ravelry")]
		Ravelry = 0xf2d9,
		[Description("React")]
		React = 0xf41b,
		[Description("ReactEurope")]
		Reacteurope = 0xf75d,
		[Description("ReadMe")]
		Readme = 0xf4d5,
		[Description("Rebel Alliance")]
		Rebel = 0xf1d0,
		[Description("Receipt")]
		Receipt = 0xf543,
		[Description("Record Vinyl")]
		RecordVinyl = 0xf8d9,
		[Description("Recycle")]
		Recycle = 0xf1b8,
		[Description("red river")]
		RedRiver = 0xf3e3,
		[Description("reddit Logo")]
		Reddit = 0xf1a1,
		[Description("reddit Alien")]
		RedditAlien = 0xf281,
		[Description("reddit Square")]
		RedditSquare = 0xf1a2,
		[Description("Redhat")]
		Redhat = 0xf7bc,
		[Description("Redo")]
		Redo = 0xf01e,
		[Description("Alternate Redo")]
		RedoAlt = 0xf2f9,
		[Description("Registered Trademark")]
		Registered = 0xf25d,
		[Description("Remove Format")]
		RemoveFormat = 0xf87d,
		[Description("Renren")]
		Renren = 0xf18b,
		[Description("Reply")]
		Reply = 0xf3e5,
		[Description("reply-all")]
		ReplyAll = 0xf122,
		[Description("replyd")]
		Replyd = 0xf3e6,
		[Description("Republican")]
		Republican = 0xf75e,
		[Description("Researchgate")]
		Researchgate = 0xf4f8,
		[Description("Resolving")]
		Resolving = 0xf3e7,
		[Description("Restroom")]
		Restroom = 0xf7bd,
		[Description("Retweet")]
		Retweet = 0xf079,
		[Description("Rev.io")]
		Rev = 0xf5b2,
		[Description("Ribbon")]
		Ribbon = 0xf4d6,
		[Description("Ring")]
		Ring = 0xf70b,
		[Description("road")]
		Road = 0xf018,
		[Description("Robot")]
		Robot = 0xf544,
		[Description("rocket")]
		Rocket = 0xf135,
		[Description("Rocket.Chat")]
		Rocketchat = 0xf3e8,
		[Description("Rockrms")]
		Rockrms = 0xf3e9,
		[Description("Route")]
		Route = 0xf4d7,
		[Description("rss")]
		Rss = 0xf09e,
		[Description("RSS Square")]
		RssSquare = 0xf143,
		[Description("Ruble Sign")]
		RubleSign = 0xf158,
		[Description("Ruler")]
		Ruler = 0xf545,
		[Description("Ruler Combined")]
		RulerCombined = 0xf546,
		[Description("Ruler Horizontal")]
		RulerHorizontal = 0xf547,
		[Description("Ruler Vertical")]
		RulerVertical = 0xf548,
		[Description("Running")]
		Running = 0xf70c,
		[Description("Indian Rupee Sign")]
		RupeeSign = 0xf156,
		[Description("Crying Face")]
		SadCry = 0xf5b3,
		[Description("Loudly Crying Face")]
		SadTear = 0xf5b4,
		[Description("Safari")]
		Safari = 0xf267,
		[Description("Salesforce")]
		Salesforce = 0xf83b,
		[Description("Sass")]
		Sass = 0xf41e,
		[Description("Satellite")]
		Satellite = 0xf7bf,
		[Description("Satellite Dish")]
		SatelliteDish = 0xf7c0,
		[Description("Save")]
		Save = 0xf0c7,
		[Description("SCHLIX")]
		Schlix = 0xf3ea,
		[Description("School")]
		School = 0xf549,
		[Description("Screwdriver")]
		Screwdriver = 0xf54a,
		[Description("Scribd")]
		Scribd = 0xf28a,
		[Description("Scroll")]
		Scroll = 0xf70e,
		[Description("Sd Card")]
		SdCard = 0xf7c2,
		[Description("Search")]
		Search = 0xf002,
		[Description("Search Dollar")]
		SearchDollar = 0xf688,
		[Description("Search Location")]
		SearchLocation = 0xf689,
		[Description("Search Minus")]
		SearchMinus = 0xf010,
		[Description("Search Plus")]
		SearchPlus = 0xf00e,
		[Description("Searchengin")]
		Searchengin = 0xf3eb,
		[Description("Seedling")]
		Seedling = 0xf4d8,
		[Description("Sellcast")]
		Sellcast = 0xf2da,
		[Description("Sellsy")]
		Sellsy = 0xf213,
		[Description("Server")]
		Server = 0xf233,
		[Description("Servicestack")]
		Servicestack = 0xf3ec,
		[Description("Shapes")]
		Shapes = 0xf61f,
		[Description("Share")]
		Share = 0xf064,
		[Description("Alternate Share")]
		ShareAlt = 0xf1e0,
		[Description("Alternate Share Square")]
		ShareAltSquare = 0xf1e1,
		[Description("Share Square")]
		ShareSquare = 0xf14d,
		[Description("Shekel Sign")]
		ShekelSign = 0xf20b,
		[Description("Alternate Shield")]
		ShieldAlt = 0xf3ed,
		[Description("Ship")]
		Ship = 0xf21a,
		[Description("Shipping Fast")]
		ShippingFast = 0xf48b,
		[Description("Shirts in Bulk")]
		Shirtsinbulk = 0xf214,
		[Description("Shoe Prints")]
		ShoePrints = 0xf54b,
		[Description("Shopify")]
		Shopify = 0xf957,
		[Description("Shopping Bag")]
		ShoppingBag = 0xf290,
		[Description("Shopping Basket")]
		ShoppingBasket = 0xf291,
		[Description("shopping-cart")]
		ShoppingCart = 0xf07a,
		[Description("Shopware")]
		Shopware = 0xf5b5,
		[Description("Shower")]
		Shower = 0xf2cc,
		[Description("Shuttle Van")]
		ShuttleVan = 0xf5b6,
		[Description("Sign")]
		Sign = 0xf4d9,
		[Description("Alternate Sign In")]
		SignInAlt = 0xf2f6,
		[Description("Sign Language")]
		SignLanguage = 0xf2a7,
		[Description("Alternate Sign Out")]
		SignOutAlt = 0xf2f5,
		[Description("signal")]
		Signal = 0xf012,
		[Description("Signature")]
		Signature = 0xf5b7,
		[Description("SIM Card")]
		SimCard = 0xf7c4,
		[Description("SimplyBuilt")]
		Simplybuilt = 0xf215,
		[Description("SISTRIX")]
		Sistrix = 0xf3ee,
		[Description("Sitemap")]
		Sitemap = 0xf0e8,
		[Description("Sith")]
		Sith = 0xf512,
		[Description("Skating")]
		Skating = 0xf7c5,
		[Description("Sketch")]
		Sketch = 0xf7c6,
		[Description("Skiing")]
		Skiing = 0xf7c9,
		[Description("Skiing Nordic")]
		SkiingNordic = 0xf7ca,
		[Description("Skull")]
		Skull = 0xf54c,
		[Description("Skull & Crossbones")]
		SkullCrossbones = 0xf714,
		[Description("skyatlas")]
		Skyatlas = 0xf216,
		[Description("Skype")]
		Skype = 0xf17e,
		[Description("Slack Logo")]
		Slack = 0xf198,
		[Description("Slack Hashtag")]
		SlackHash = 0xf3ef,
		[Description("Slash")]
		Slash = 0xf715,
		[Description("Sleigh")]
		Sleigh = 0xf7cc,
		[Description("Horizontal Sliders")]
		SlidersH = 0xf1de,
		[Description("Slideshare")]
		Slideshare = 0xf1e7,
		[Description("Smiling Face")]
		Smile = 0xf118,
		[Description("Beaming Face With Smiling Eyes")]
		SmileBeam = 0xf5b8,
		[Description("Winking Face")]
		SmileWink = 0xf4da,
		[Description("Smog")]
		Smog = 0xf75f,
		[Description("Smoking")]
		Smoking = 0xf48d,
		[Description("Smoking Ban")]
		SmokingBan = 0xf54d,
		[Description("SMS")]
		Sms = 0xf7cd,
		[Description("Snapchat")]
		Snapchat = 0xf2ab,
		[Description("Snapchat Ghost")]
		SnapchatGhost = 0xf2ac,
		[Description("Snapchat Square")]
		SnapchatSquare = 0xf2ad,
		[Description("Snowboarding")]
		Snowboarding = 0xf7ce,
		[Description("Snowflake")]
		Snowflake = 0xf2dc,
		[Description("Snowman")]
		Snowman = 0xf7d0,
		[Description("Snowplow")]
		Snowplow = 0xf7d2,
		[Description("Socks")]
		Socks = 0xf696,
		[Description("Solar Panel")]
		SolarPanel = 0xf5ba,
		[Description("Sort")]
		Sort = 0xf0dc,
		[Description("Sort Alphabetical Down")]
		SortAlphaDown = 0xf15d,
		[Description("Alternate Sort Alphabetical Down")]
		SortAlphaDownAlt = 0xf881,
		[Description("Sort Alphabetical Up")]
		SortAlphaUp = 0xf15e,
		[Description("Alternate Sort Alphabetical Up")]
		SortAlphaUpAlt = 0xf882,
		[Description("Sort Amount Down")]
		SortAmountDown = 0xf160,
		[Description("Alternate Sort Amount Down")]
		SortAmountDownAlt = 0xf884,
		[Description("Sort Amount Up")]
		SortAmountUp = 0xf161,
		[Description("Alternate Sort Amount Up")]
		SortAmountUpAlt = 0xf885,
		[Description("Sort Down (Descending)")]
		SortDown = 0xf0dd,
		[Description("Sort Numeric Down")]
		SortNumericDown = 0xf162,
		[Description("Alternate Sort Numeric Down")]
		SortNumericDownAlt = 0xf886,
		[Description("Sort Numeric Up")]
		SortNumericUp = 0xf163,
		[Description("Alternate Sort Numeric Up")]
		SortNumericUpAlt = 0xf887,
		[Description("Sort Up (Ascending)")]
		SortUp = 0xf0de,
		[Description("SoundCloud")]
		Soundcloud = 0xf1be,
		[Description("Sourcetree")]
		Sourcetree = 0xf7d3,
		[Description("Spa")]
		Spa = 0xf5bb,
		[Description("Space Shuttle")]
		SpaceShuttle = 0xf197,
		[Description("Speakap")]
		Speakap = 0xf3f3,
		[Description("Speaker Deck")]
		SpeakerDeck = 0xf83c,
		[Description("Spell Check")]
		SpellCheck = 0xf891,
		[Description("Spider")]
		Spider = 0xf717,
		[Description("Spinner")]
		Spinner = 0xf110,
		[Description("Splotch")]
		Splotch = 0xf5bc,
		[Description("Spotify")]
		Spotify = 0xf1bc,
		[Description("Spray Can")]
		SprayCan = 0xf5bd,
		[Description("Square")]
		Square = 0xf0c8,
		[Description("Square Full")]
		SquareFull = 0xf45c,
		[Description("Alternate Square Root")]
		SquareRootAlt = 0xf698,
		[Description("Squarespace")]
		Squarespace = 0xf5be,
		[Description("Stack Exchange")]
		StackExchange = 0xf18d,
		[Description("Stack Overflow")]
		StackOverflow = 0xf16c,
		[Description("Stackpath")]
		Stackpath = 0xf842,
		[Description("Stamp")]
		Stamp = 0xf5bf,
		[Description("Star")]
		Star = 0xf005,
		[Description("Star and Crescent")]
		StarAndCrescent = 0xf699,
		[Description("star-half")]
		StarHalf = 0xf089,
		[Description("Alternate Star Half")]
		StarHalfAlt = 0xf5c0,
		[Description("Star of David")]
		StarOfDavid = 0xf69a,
		[Description("Star of Life")]
		StarOfLife = 0xf621,
		[Description("StayLinked")]
		Staylinked = 0xf3f5,
		[Description("Steam")]
		Steam = 0xf1b6,
		[Description("Steam Square")]
		SteamSquare = 0xf1b7,
		[Description("Steam Symbol")]
		SteamSymbol = 0xf3f6,
		[Description("step-backward")]
		StepBackward = 0xf048,
		[Description("step-forward")]
		StepForward = 0xf051,
		[Description("Stethoscope")]
		Stethoscope = 0xf0f1,
		[Description("Sticker Mule")]
		StickerMule = 0xf3f7,
		[Description("Sticky Note")]
		StickyNote = 0xf249,
		[Description("stop")]
		Stop = 0xf04d,
		[Description("Stop Circle")]
		StopCircle = 0xf28d,
		[Description("Stopwatch")]
		Stopwatch = 0xf2f2,
		[Description("Store")]
		Store = 0xf54e,
		[Description("Alternate Store")]
		StoreAlt = 0xf54f,
		[Description("Strava")]
		Strava = 0xf428,
		[Description("Stream")]
		Stream = 0xf550,
		[Description("Street View")]
		StreetView = 0xf21d,
		[Description("Strikethrough")]
		Strikethrough = 0xf0cc,
		[Description("Stripe")]
		Stripe = 0xf429,
		[Description("Stripe S")]
		StripeS = 0xf42a,
		[Description("Stroopwafel")]
		Stroopwafel = 0xf551,
		[Description("Studio Vinari")]
		Studiovinari = 0xf3f8,
		[Description("StumbleUpon Logo")]
		Stumbleupon = 0xf1a4,
		[Description("StumbleUpon Circle")]
		StumbleuponCircle = 0xf1a3,
		[Description("subscript")]
		Subscript = 0xf12c,
		[Description("Subway")]
		Subway = 0xf239,
		[Description("Suitcase")]
		Suitcase = 0xf0f2,
		[Description("Suitcase Rolling")]
		SuitcaseRolling = 0xf5c1,
		[Description("Sun")]
		Sun = 0xf185,
		[Description("Superpowers")]
		Superpowers = 0xf2dd,
		[Description("superscript")]
		Superscript = 0xf12b,
		[Description("Supple")]
		Supple = 0xf3f9,
		[Description("Hushed Face")]
		Surprise = 0xf5c2,
		[Description("Suse")]
		Suse = 0xf7d6,
		[Description("Swatchbook")]
		Swatchbook = 0xf5c3,
		[Description("Swift")]
		Swift = 0xf8e1,
		[Description("Swimmer")]
		Swimmer = 0xf5c4,
		[Description("Swimming Pool")]
		SwimmingPool = 0xf5c5,
		[Description("Symfony")]
		Symfony = 0xf83d,
		[Description("Synagogue")]
		Synagogue = 0xf69b,
		[Description("Sync")]
		Sync = 0xf021,
		[Description("Alternate Sync")]
		SyncAlt = 0xf2f1,
		[Description("Syringe")]
		Syringe = 0xf48e,
		[Description("table")]
		Table = 0xf0ce,
		[Description("Table Tennis")]
		TableTennis = 0xf45d,
		[Description("tablet")]
		Tablet = 0xf10a,
		[Description("Alternate Tablet")]
		TabletAlt = 0xf3fa,
		[Description("Tablets")]
		Tablets = 0xf490,
		[Description("Alternate Tachometer")]
		TachometerAlt = 0xf3fd,
		[Description("tag")]
		Tag = 0xf02b,
		[Description("tags")]
		Tags = 0xf02c,
		[Description("Tape")]
		Tape = 0xf4db,
		[Description("Tasks")]
		Tasks = 0xf0ae,
		[Description("Taxi")]
		Taxi = 0xf1ba,
		[Description("TeamSpeak")]
		Teamspeak = 0xf4f9,
		[Description("Teeth")]
		Teeth = 0xf62e,
		[Description("Teeth Open")]
		TeethOpen = 0xf62f,
		[Description("Telegram")]
		Telegram = 0xf2c6,
		[Description("Telegram Plane")]
		TelegramPlane = 0xf3fe,
		[Description("High Temperature")]
		TemperatureHigh = 0xf769,
		[Description("Low Temperature")]
		TemperatureLow = 0xf76b,
		[Description("Tencent Weibo")]
		TencentWeibo = 0xf1d5,
		[Description("Tenge")]
		Tenge = 0xf7d7,
		[Description("Terminal")]
		Terminal = 0xf120,
		[Description("text-height")]
		TextHeight = 0xf034,
		[Description("Text Width")]
		TextWidth = 0xf035,
		[Description("th")]
		Th = 0xf00a,
		[Description("th-large")]
		ThLarge = 0xf009,
		[Description("th-list")]
		ThList = 0xf00b,
		[Description("The Red Yeti")]
		TheRedYeti = 0xf69d,
		[Description("Theater Masks")]
		TheaterMasks = 0xf630,
		[Description("Themeco")]
		Themeco = 0xf5c6,
		[Description("ThemeIsle")]
		Themeisle = 0xf2b2,
		[Description("Thermometer")]
		Thermometer = 0xf491,
		[Description("Thermometer Empty")]
		ThermometerEmpty = 0xf2cb,
		[Description("Thermometer Full")]
		ThermometerFull = 0xf2c7,
		[Description("Thermometer 1/2 Full")]
		ThermometerHalf = 0xf2c9,
		[Description("Thermometer 1/4 Full")]
		ThermometerQuarter = 0xf2ca,
		[Description("Thermometer 3/4 Full")]
		ThermometerThreeQuarters = 0xf2c8,
		[Description("Think Peaks")]
		ThinkPeaks = 0xf731,
		[Description("thumbs-down")]
		ThumbsDown = 0xf165,
		[Description("thumbs-up")]
		ThumbsUp = 0xf164,
		[Description("Thumbtack")]
		Thumbtack = 0xf08d,
		[Description("Alternate Ticket")]
		TicketAlt = 0xf3ff,
		[Description("Times")]
		Times = 0xf00d,
		[Description("Times Circle")]
		TimesCircle = 0xf057,
		[Description("tint")]
		Tint = 0xf043,
		[Description("Tint Slash")]
		TintSlash = 0xf5c7,
		[Description("Tired Face")]
		Tired = 0xf5c8,
		[Description("Toggle Off")]
		ToggleOff = 0xf204,
		[Description("Toggle On")]
		ToggleOn = 0xf205,
		[Description("Toilet")]
		Toilet = 0xf7d8,
		[Description("Toilet Paper")]
		ToiletPaper = 0xf71e,
		[Description("Toolbox")]
		Toolbox = 0xf552,
		[Description("Tools")]
		Tools = 0xf7d9,
		[Description("Tooth")]
		Tooth = 0xf5c9,
		[Description("Torah")]
		Torah = 0xf6a0,
		[Description("Torii Gate")]
		ToriiGate = 0xf6a1,
		[Description("Tractor")]
		Tractor = 0xf722,
		[Description("Trade Federation")]
		TradeFederation = 0xf513,
		[Description("Trademark")]
		Trademark = 0xf25c,
		[Description("Traffic Light")]
		TrafficLight = 0xf637,
		[Description("Trailer")]
		Trailer = 0xf941,
		[Description("Train")]
		Train = 0xf238,
		[Description("Tram")]
		Tram = 0xf7da,
		[Description("Transgender")]
		Transgender = 0xf224,
		[Description("Alternate Transgender")]
		TransgenderAlt = 0xf225,
		[Description("Trash")]
		Trash = 0xf1f8,
		[Description("Alternate Trash")]
		TrashAlt = 0xf2ed,
		[Description("Trash Restore")]
		TrashRestore = 0xf829,
		[Description("Alternative Trash Restore")]
		TrashRestoreAlt = 0xf82a,
		[Description("Tree")]
		Tree = 0xf1bb,
		[Description("Trello")]
		Trello = 0xf181,
		[Description("TripAdvisor")]
		Tripadvisor = 0xf262,
		[Description("trophy")]
		Trophy = 0xf091,
		[Description("truck")]
		Truck = 0xf0d1,
		[Description("Truck Loading")]
		TruckLoading = 0xf4de,
		[Description("Truck Monster")]
		TruckMonster = 0xf63b,
		[Description("Truck Moving")]
		TruckMoving = 0xf4df,
		[Description("Truck Side")]
		TruckPickup = 0xf63c,
		[Description("T-Shirt")]
		Tshirt = 0xf553,
		[Description("TTY")]
		Tty = 0xf1e4,
		[Description("Tumblr")]
		Tumblr = 0xf173,
		[Description("Tumblr Square")]
		TumblrSquare = 0xf174,
		[Description("Television")]
		Tv = 0xf26c,
		[Description("Twitch")]
		Twitch = 0xf1e8,
		[Description("Twitter")]
		Twitter = 0xf099,
		[Description("Twitter Square")]
		TwitterSquare = 0xf081,
		[Description("Typo3")]
		Typo3 = 0xf42b,
		[Description("Uber")]
		Uber = 0xf402,
		[Description("Ubuntu")]
		Ubuntu = 0xf7df,
		[Description("UIkit")]
		Uikit = 0xf403,
		[Description("Umbraco")]
		Umbraco = 0xf8e8,
		[Description("Umbrella")]
		Umbrella = 0xf0e9,
		[Description("Umbrella Beach")]
		UmbrellaBeach = 0xf5ca,
		[Description("Underline")]
		Underline = 0xf0cd,
		[Description("Undo")]
		Undo = 0xf0e2,
		[Description("Alternate Undo")]
		UndoAlt = 0xf2ea,
		[Description("Uniregistry")]
		Uniregistry = 0xf404,
		[Description("Unity 3D")]
		Unity = 0xf949,
		[Description("Universal Access")]
		UniversalAccess = 0xf29a,
		[Description("University")]
		University = 0xf19c,
		[Description("unlink")]
		Unlink = 0xf127,
		[Description("unlock")]
		Unlock = 0xf09c,
		[Description("Alternate Unlock")]
		UnlockAlt = 0xf13e,
		[Description("Untappd")]
		Untappd = 0xf405,
		[Description("Upload")]
		Upload = 0xf093,
		[Description("UPS")]
		Ups = 0xf7e0,
		[Description("USB")]
		Usb = 0xf287,
		[Description("User")]
		User = 0xf007,
		[Description("Alternate User")]
		UserAlt = 0xf406,
		[Description("Alternate User Slash")]
		UserAltSlash = 0xf4fa,
		[Description("User Astronaut")]
		UserAstronaut = 0xf4fb,
		[Description("User Check")]
		UserCheck = 0xf4fc,
		[Description("User Circle")]
		UserCircle = 0xf2bd,
		[Description("User Clock")]
		UserClock = 0xf4fd,
		[Description("User Cog")]
		UserCog = 0xf4fe,
		[Description("User Edit")]
		UserEdit = 0xf4ff,
		[Description("User Friends")]
		UserFriends = 0xf500,
		[Description("User Graduate")]
		UserGraduate = 0xf501,
		[Description("User Injured")]
		UserInjured = 0xf728,
		[Description("User Lock")]
		UserLock = 0xf502,
		[Description("Doctor")]
		UserMd = 0xf0f0,
		[Description("User Minus")]
		UserMinus = 0xf503,
		[Description("User Ninja")]
		UserNinja = 0xf504,
		[Description("Nurse")]
		UserNurse = 0xf82f,
		[Description("User Plus")]
		UserPlus = 0xf234,
		[Description("User Secret")]
		UserSecret = 0xf21b,
		[Description("User Shield")]
		UserShield = 0xf505,
		[Description("User Slash")]
		UserSlash = 0xf506,
		[Description("User Tag")]
		UserTag = 0xf507,
		[Description("User Tie")]
		UserTie = 0xf508,
		[Description("Remove User")]
		UserTimes = 0xf235,
		[Description("Users")]
		Users = 0xf0c0,
		[Description("Users Cog")]
		UsersCog = 0xf509,
		[Description("United States Postal Service")]
		Usps = 0xf7e1,
		[Description("us-Sunnah Foundation")]
		Ussunnah = 0xf407,
		[Description("Utensil Spoon")]
		UtensilSpoon = 0xf2e5,
		[Description("Utensils")]
		Utensils = 0xf2e7,
		[Description("Vaadin")]
		Vaadin = 0xf408,
		[Description("Vector Square")]
		VectorSquare = 0xf5cb,
		[Description("Venus")]
		Venus = 0xf221,
		[Description("Venus Double")]
		VenusDouble = 0xf226,
		[Description("Venus Mars")]
		VenusMars = 0xf228,
		[Description("Viacoin")]
		Viacoin = 0xf237,
		[Description("Video")]
		Viadeo = 0xf2a9,
		[Description("Video Square")]
		ViadeoSquare = 0xf2aa,
		[Description("Vial")]
		Vial = 0xf492,
		[Description("Vials")]
		Vials = 0xf493,
		[Description("Viber")]
		Viber = 0xf409,
		[Description("Video")]
		Video = 0xf03d,
		[Description("Video Slash")]
		VideoSlash = 0xf4e2,
		[Description("Vihara")]
		Vihara = 0xf6a7,
		[Description("Vimeo")]
		Vimeo = 0xf40a,
		[Description("Vimeo Square")]
		VimeoSquare = 0xf194,
		[Description("Vimeo")]
		VimeoV = 0xf27d,
		[Description("Vine")]
		Vine = 0xf1ca,
		[Description("VK")]
		Vk = 0xf189,
		[Description("VNV")]
		Vnv = 0xf40b,
		[Description("Voicemail")]
		Voicemail = 0xf897,
		[Description("Volleyball Ball")]
		VolleyballBall = 0xf45f,
		[Description("Volume Down")]
		VolumeDown = 0xf027,
		[Description("Volume Mute")]
		VolumeMute = 0xf6a9,
		[Description("Volume Off")]
		VolumeOff = 0xf026,
		[Description("Volume Up")]
		VolumeUp = 0xf028,
		[Description("Vote Yea")]
		VoteYea = 0xf772,
		[Description("Cardboard VR")]
		VrCardboard = 0xf729,
		[Description("Vue.js")]
		Vuejs = 0xf41f,
		[Description("Walking")]
		Walking = 0xf554,
		[Description("Wallet")]
		Wallet = 0xf555,
		[Description("Warehouse")]
		Warehouse = 0xf494,
		[Description("Water")]
		Water = 0xf773,
		[Description("Square Wave")]
		WaveSquare = 0xf83e,
		[Description("Waze")]
		Waze = 0xf83f,
		[Description("Weebly")]
		Weebly = 0xf5cc,
		[Description("Weibo")]
		Weibo = 0xf18a,
		[Description("Weight")]
		Weight = 0xf496,
		[Description("Hanging Weight")]
		WeightHanging = 0xf5cd,
		[Description("Weixin (WeChat)")]
		Weixin = 0xf1d7,
		[Description("What's App")]
		Whatsapp = 0xf232,
		[Description("What's App Square")]
		WhatsappSquare = 0xf40c,
		[Description("Wheelchair")]
		Wheelchair = 0xf193,
		[Description("WHMCS")]
		Whmcs = 0xf40d,
		[Description("WiFi")]
		Wifi = 0xf1eb,
		[Description("Wikipedia W")]
		WikipediaW = 0xf266,
		[Description("Wind")]
		Wind = 0xf72e,
		[Description("Window Close")]
		WindowClose = 0xf410,
		[Description("Window Maximize")]
		WindowMaximize = 0xf2d0,
		[Description("Window Minimize")]
		WindowMinimize = 0xf2d1,
		[Description("Window Restore")]
		WindowRestore = 0xf2d2,
		[Description("Windows")]
		Windows = 0xf17a,
		[Description("Wine Bottle")]
		WineBottle = 0xf72f,
		[Description("Wine Glass")]
		WineGlass = 0xf4e3,
		[Description("Alternate Wine Glas")]
		WineGlassAlt = 0xf5ce,
		[Description("Wix")]
		Wix = 0xf5cf,
		[Description("Wizards of the Coast")]
		WizardsOfTheCoast = 0xf730,
		[Description("Wolf Pack Battalion")]
		WolfPackBattalion = 0xf514,
		[Description("Won Sign")]
		WonSign = 0xf159,
		[Description("WordPress Logo")]
		Wordpress = 0xf19a,
		[Description("Wordpress Simple")]
		WordpressSimple = 0xf411,
		[Description("WPBeginner")]
		Wpbeginner = 0xf297,
		[Description("WPExplorer")]
		Wpexplorer = 0xf2de,
		[Description("WPForms")]
		Wpforms = 0xf298,
		[Description("wpressr")]
		Wpressr = 0xf3e4,
		[Description("Wrench")]
		Wrench = 0xf0ad,
		[Description("X-Ray")]
		XRay = 0xf497,
		[Description("Xbox")]
		Xbox = 0xf412,
		[Description("Xing")]
		Xing = 0xf168,
		[Description("Xing Square")]
		XingSquare = 0xf169,
		[Description("Y Combinator")]
		YCombinator = 0xf23b,
		[Description("Yahoo Logo")]
		Yahoo = 0xf19e,
		[Description("Yammer")]
		Yammer = 0xf840,
		[Description("Yandex")]
		Yandex = 0xf413,
		[Description("Yandex International")]
		YandexInternational = 0xf414,
		[Description("Yarn")]
		Yarn = 0xf7e3,
		[Description("Yelp")]
		Yelp = 0xf1e9,
		[Description("Yen Sign")]
		YenSign = 0xf157,
		[Description("Yin Yang")]
		YinYang = 0xf6ad,
		[Description("Yoast")]
		Yoast = 0xf2b1,
		[Description("YouTube")]
		Youtube = 0xf167,
		[Description("YouTube Square")]
		YoutubeSquare = 0xf431,
		[Description("Zhihu")]
		Zhihu = 0xf63f,
	}
}
